services:
  mcp:
    image: mcp_deerflow:260915
    ports:
      - "8084:8084"
    # network_mode: "host"
    volumes:
      - "./src_deerflow/:/app/src_deerflow"
    environment:
      - PYTHONPATH=/app
    command: ["python", "/app/src_deerflow/mcp_server.py"]
    # command: ["uvicorn", "src/mcp_server:app", "--host", "0.0.0.0", "--port", "8083"]
    # ["uvicorn", "mcp_server:app", "--host", "0.0.0.0", "--port", "8083"] 